include:
- functions/coordinator/main.py
kind: ArchiveUploadSpec
name: coordinator-py

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: coordinator-py-15w2
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://coordinator-py
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: coordinator
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 1
      MinScale: 0
      TargetCPUPercent: 80
    StrategyType: execution
  configmaps: null
  environment:
    name: python
    namespace: default
  package:
    packageref:
      name: coordinator-py-15w2
      namespace: default
  resources: {}
  secrets: null
