include:
- functions/translation/main.py
kind: ArchiveUploadSpec
name: translation-py

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: translation-py-s0yv
  namespace: default
spec:
  environment:
    name: python
    namespace: default
  deployment:
    checksum: {}
    type: url
    url: archive://translation-py
status:
  buildstatus: none

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: translation
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 1
      MinScale: 0
      TargetCPUPercent: 80
    StrategyType: execution
  configmaps: null
  environment:
    name: python
    namespace: default
  package:
    packageref:
      name: translation-py-s0yv
      namespace: default
  resources: {}
  secrets:
  - name: google-api-key
    namespace: default
