apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: coordinator
  namespace: default
spec:
  functionref:
    name: coordinator
    type: name
  host: ""
  method: POST
  relativeurl: /coordinator
